os:
  - linux

sudo: required
dist: trusty

language: node_js

node_js:
  - '4.4.1'

before_install:
  - "sudo apt-get update;sudo apt-get install -y curl libssl-dev build-essential g++ libkrb5-dev"
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-10gen
  - sleep 15
  - mongo --version

services:
  - mongodb

